exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://vcantarella.github.io/HyVR.jl/stable$",
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
