[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
HyVR = "9004e290-3ebd-56de-8ed7-b9c23420ed7d"

[compat]
Documenter = "1"

[sources]
HyVR = {path = ".."}
